version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      # Use polling for hot reloading to work across the docker container boundary
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.expo
    depends_on:
      - backend
